graphhopper:
  datareader.file: /data/netherlands-latest.osm.pbf
  graph.location: /graph-cache

  custom_models.directory: /config

  import.osm.ignored_highways: motorway, motorway_link, trunk, trunk_link, raceway

  graph.encoded_values: road_class

  profiles:
    - name: moped
      base: car
      weighting: custom
      custom_model_files:
        - moped-rules.json

  server:
    custom_models.enabled: true